<?php
$orto_slider_sc = orto_get_theme_option( 'front_page_title_shortcode' );
if ( ! empty( $orto_slider_sc ) && strpos( $orto_slider_sc, '[' ) !== false && strpos( $orto_slider_sc, ']' ) !== false ) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider
		<?php
		if ( orto_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
	">
	<?php
		// Add anchor
		$orto_anchor_icon = orto_get_theme_option( 'front_page_title_anchor_icon' );
		$orto_anchor_text = orto_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $orto_anchor_icon ) || ! empty( $orto_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $orto_anchor_icon ) ? ' icon="' . esc_attr( $orto_anchor_icon ) . '"' : '' )
									. ( ! empty( $orto_anchor_text ) ? ' title="' . esc_attr( $orto_anchor_text ) . '"' : '' )
									. ']'
		);
	}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode( $orto_slider_sc );
	?>
	</div>
	<?php

} else {

	?>
	<div class="front_page_section front_page_section_title
		<?php
		$orto_scheme = orto_get_theme_option( 'front_page_title_scheme' );
		if ( ! empty( $orto_scheme ) && ! orto_is_inherit( $orto_scheme ) ) {
			echo ' scheme_' . esc_attr( $orto_scheme );
		}
		echo ' front_page_section_paddings_' . esc_attr( orto_get_theme_option( 'front_page_title_paddings' ) );
		if ( orto_get_theme_option( 'front_page_title_stack' ) ) {
			echo ' sc_stack_section_on';
		}
		?>
		"
		<?php
		$orto_css      = '';
		$orto_bg_image = orto_get_theme_option( 'front_page_title_bg_image' );
		if ( ! empty( $orto_bg_image ) ) {
			$orto_css .= 'background-image: url(' . esc_url( orto_get_attachment_url( $orto_bg_image ) ) . ');';
		}
		if ( ! empty( $orto_css ) ) {
			echo ' style="' . esc_attr( $orto_css ) . '"';
		}
		?>
	>
	<?php
		// Add anchor
		$orto_anchor_icon = orto_get_theme_option( 'front_page_title_anchor_icon' );
		$orto_anchor_text = orto_get_theme_option( 'front_page_title_anchor_text' );
	if ( ( ! empty( $orto_anchor_icon ) || ! empty( $orto_anchor_text ) ) && shortcode_exists( 'trx_sc_anchor' ) ) {
		echo do_shortcode(
			'[trx_sc_anchor id="front_page_section_title"'
									. ( ! empty( $orto_anchor_icon ) ? ' icon="' . esc_attr( $orto_anchor_icon ) . '"' : '' )
									. ( ! empty( $orto_anchor_text ) ? ' title="' . esc_attr( $orto_anchor_text ) . '"' : '' )
									. ']'
		);
	}
	?>
		<div class="front_page_section_inner front_page_section_title_inner
		<?php
		if ( orto_get_theme_option( 'front_page_title_fullheight' ) ) {
			echo ' orto-full-height sc_layouts_flex sc_layouts_columns_middle';
		}
		?>
			"
			<?php
			$orto_css      = '';
			$orto_bg_mask  = orto_get_theme_option( 'front_page_title_bg_mask' );
			$orto_bg_color_type = orto_get_theme_option( 'front_page_title_bg_color_type' );
			if ( 'custom' == $orto_bg_color_type ) {
				$orto_bg_color = orto_get_theme_option( 'front_page_title_bg_color' );
			} elseif ( 'scheme_bg_color' == $orto_bg_color_type ) {
				$orto_bg_color = orto_get_scheme_color( 'bg_color', $orto_scheme );
			} else {
				$orto_bg_color = '';
			}
			if ( ! empty( $orto_bg_color ) && $orto_bg_mask > 0 ) {
				$orto_css .= 'background-color: ' . esc_attr(
					1 == $orto_bg_mask ? $orto_bg_color : orto_hex2rgba( $orto_bg_color, $orto_bg_mask )
				) . ';';
			}
			if ( ! empty( $orto_css ) ) {
				echo ' style="' . esc_attr( $orto_css ) . '"';
			}
			?>
		>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$orto_caption = orto_get_theme_option( 'front_page_title_caption' );
				if ( ! empty( $orto_caption ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo ! empty( $orto_caption ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( $orto_caption, 'orto_kses_content' ); ?></h1>
					<?php
				}

				// Description (text)
				$orto_description = orto_get_theme_option( 'front_page_title_description' );
				if ( ! empty( $orto_description ) || ( current_user_can( 'edit_theme_options' ) && is_customize_preview() ) ) {
					?>
					<div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo ! empty( $orto_description ) ? 'filled' : 'empty'; ?>"><?php echo wp_kses( wpautop( $orto_description ), 'orto_kses_content' ); ?></div>
					<?php
				}

				// Buttons
				if ( orto_get_theme_option( 'front_page_title_button1_link' ) != '' || orto_get_theme_option( 'front_page_title_button2_link' ) != '' ) {
					?>
					<div class="front_page_section_buttons front_page_section_title_buttons">
					<?php
						orto_show_layout( orto_customizer_partial_refresh_front_page_title_button1_link() );
						orto_show_layout( orto_customizer_partial_refresh_front_page_title_button2_link() );
					?>
					</div>
					<?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}
